using System.Runtime.InteropServices;
using System.Windows;

// Only WPF-specific attributes live here. Version-related attributes
// (AssemblyVersion, AssemblyFileVersion, AssemblyInformationalVersion,
// Company, Product, Copyright, etc.) are auto-generated by the SDK
// from the values in Directory.Build.props and stamped into the Win32
// VERSIONINFO resource. Auto-generation is enabled (GenerateAssemblyInfo
// is left at its default of true) precisely so the PE version resource
// is written and FileVersionInfo / Assembly.GetName().Version both
// return the actual build version. Do not add version-related
// attributes here without first disabling GenerateAssemblyInfo in the
// csproj, or the build will fail with CS0579.

[assembly: ComVisible(false)]
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,
    ResourceDictionaryLocation.SourceAssembly
)]
