# SpeedShare Proguard / R8 rules
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable

# Keep models for JSON serialization
-keep class com.example.speedshareandroid.models.** { *; }

# Keep Coroutines internals
-dontwarn kotlinx.coroutines.**
-keepclassmembers class kotlinx.coroutines.** { *; }

# FileProvider is looked up by the PackageManager via the authority
# string at install time. R8 may rename the class symbol, but the
# manifest's <provider android:name=...> reference is a literal string,
# so we keep the class symbol just in case R8's manifest-aware
# transform misses it.
-keep class androidx.core.content.FileProvider { *; }

# DocumentsContract.* and provider IPC: kept by the platform's
# consumer rules, but we keep an explicit pin to avoid any surprises
# in newer R8 versions.
-keep class androidx.documentfile.provider.** { *; }
-dontwarn androidx.documentfile.**

# BuildConfig is referenced via fields generated by AGP; keep all
# fields so the applicationId/versionName lookups in app code work
# after R8 inlining.
-keep class com.example.speedshareandroid.BuildConfig { *; }

# Strip Log.d / Log.v in release to keep the APK lean, but keep
# Log.w / Log.e so update and transfer failures remain visible
# in `adb logcat`.
-assumenosideeffects class android.util.Log {
    public static int d(...);
    public static int v(...);
    public static int i(...);
}
